[isnational]
type = "point-estimate"
value = 1

[duration]
type = "point-estimate"
value = 84

[icu_bed_usage]
type = "point-estimate"
value = -1

[intervention_shift]
type = "point-estimate"
value = 0