data_directory: .
run_id: local_test
access_log: access-{run_id}.yaml
fail_on_hash_mismatch: True
run_metadata:
  default_input_namespace: LSHTM
read:
  - where:
      data_product: school/holiday_rates
  - where:
      data_product: school/school_terms
  - where:
      data_product: contact_matrices/subregion
  - where:
      data_product: contact_matrices/national
  - where:
      data_product: population/population_sizes
  - where:
      data_product: lockdown/triggers
  - where:
      data_product: run-configuration/time
  - where:
      data_product: run-configuration/seeding
  - where:
      data_product: lockdown/config
  - where:
      data_product: distributions/R0
  - where:
      data_product: distributions/to_icu
  - where:
      data_product: distributions/to_non_icu
  - where:
      data_product: distributions/dIs
  - where:
      data_product: distributions/dIa
  - where:
      data_product: distributions/dIp
  - where:
      data_product: distributions/dE
  - where:
      data_product: distributions/ip_to_death
  - where:
      data_product: distributions/ip_to_hosp
  - where:
      data_product: fixed-parameters/tau
  - where:
      data_product: fixed-parameters/rho
  - where:
      data_product: fixed-parameters/relative_infectiousness
  - where:
      data_product: fixed-parameters/delay_gamma