name: LSHTM Model

on: [ push ]

jobs:
  build:
    name : ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
          fail-fast: false
          matrix:
            os:  ['ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v2

      - name: Install R (Ubuntu)
        run : |
              sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
              sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/'
              sudo apt update
              sudo apt install r-base r-base-core r-recommended
        if: matrix.os == 'ubuntu-latest'

      - name: Install R (macOS)
        run : |
              rm /usr/local/bin/gfortran
              brew install r gdal openssl hdf5 udunits proj
        if: matrix.os == 'macos-latest'

      - name : Install System Requirements (Ubuntu)
        run : sudo apt-get install libxml2-dev libcurl4-openssl-dev libnlopt-dev curl libgsl-dev libhdf5-dev libudunits2-dev libgdal-dev -y
        if: matrix.os == 'ubuntu-latest'

      - name: Install R library Requirements (Ubuntu)
        run: |
             sudo apt-get install apt-transport-https software-properties-common -y
        if: matrix.os == 'ubuntu-latest'

      - name: Install Required Libraries
        env: 
              DEBIAN_FRONTEND: noninteractive
        run: |
              install.packages("remotes")
              library(remotes)
              remotes::install_github("traversc/qs@legacy")
              install.packages("curl")
              install.packages("httr")
              install.packages("rvest")
              install.packages("rlang")
              install.packages("stringr")
              install.packages("data.table")
              install.packages("ggplot2")
              install.packages("lubridate")
              install.packages("nloptr")
              install.packages("HDInterval")
              install.packages("cowplot")
              install.packages("testit")
              install.packages("readxl")
              install.packages("ini")
              install.packages("tidyverse")
              install.packages("magrittr")
              install.packages("lubridate")
              install.packages("testit")
              install.packages("RcppGSL")
              install.packages("reticulate")
              remotes::install_github("ScottishCovidResponse/SCRCdataAPI")
        shell: sudo Rscript {0}
        
      - name: Run Model Locally in Dump Mode
        run: Rscript run_model.R 1 --local --dump

      - name: Test Outputs
        run: Rscript tests/regression/test_params.R

      - name: Test Local Vanilla Model Run (Region = Glasgow City, 10 realisations)
        run: Rscript run_model.R 10 --local

      - name: Install pip and SCRC Data Pipeline
        run : |
              sudo apt-get install python3.6 python3-pip
              sudo pip install -r SCRC/Python/requirements.txt
        if: matrix.os == 'ubuntu-latest'

      - name: Test Remote Vanilla Model Run (Region = Glasgow City, 10 realisations)
        run: Rscript run_model.R 10
