name: LSHTM Model

on: [ push ]

jobs:
  build:
    name : ${{ matrix.config.os }} R Version '${{ matrix.config.r }}' Python ${{ matrix.config.python }}
    runs-on: ${{ matrix.config.os }}
    strategy:
          fail-fast: false
          matrix:
            config:
              - { os : 'ubuntu-20.04', python : '3.8', r : 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest" }
              #- { os : 'macos-latest', python : '3.8', r : 'release' } #FIXME: Regression test fails due to precision
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python }}
       
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name : Install System Requirements (Ubuntu)
        run : sudo apt-get install libxml2-dev libcurl4-openssl-dev libnlopt-dev curl libgsl-dev libhdf5-dev libudunits2-dev libgdal-dev -y -q
        if: matrix.config.os == 'ubuntu-20.04'

      - name : Install System Requirements (macOS)
        run : |
              rm /usr/local/bin/gfortran
              brew install libxml2 curl curl-openssl nlopt gsl hdf5 udunits gdal 
        if : matrix.config.os == 'macos-latest'

      - name: Install R library Requirements (Ubuntu)
        run: |
             sudo apt-get install apt-transport-https software-properties-common -y -q
        if: matrix.config.os == 'ubuntu-20.04'

      - name: Install Required Libraries
        env: 
              DEBIAN_FRONTEND: noninteractive
        run: sudo Rscript SCRC/R/requirements.R --ncpus=2 --quiet
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run Model Locally in Dump Mode
        run: Rscript run_model.R 1 --local --dump

      - name: Test Outputs
        run: Rscript tests/regression/test_params.R
      
      - name: Install Pip and Require Modules
        run : |
              sudo apt-get install python3-pip python3-setuptools
              python3 -m pip install -q pandas dataclasses pyyaml
        if: matrix.config.os == 'ubuntu-20.04'

      - name: Test Local Vanilla Model Run (Region = Glasgow City, 10 realisations)
        run: Rscript run_model.R 10 --local

      - name: Install SCRC Data Pipeline
        run : |
              python3 -m pip install -q -r SCRC/Python/requirements.txt
        if: matrix.config.os == 'ubuntu-20.04'

      - name: Test Remote Vanilla Model Run (Region = Glasgow City, 10 realisations)
        run: Rscript run_model.R 10

      - name: Test Output Files
        run: |
             library(SCRCdataAPI)
             dyn_sum_base <- read_table(file="local_test.h5", path="SCRC/pipeline_data/lshtm_outputs/dynamics_summary", component="base")
             dyn_sum_base[1,]$lower
             dyn_ts_base_R <- read_table(file="local_test.h5", path="SCRC/pipeline_data/lshtm_outputs/dynamics_time_series", component="Base_R_time_series")
             dyn_ts_base_R[1,][[366]]
             cases_base <- read_table(file="local_test.h5", path="SCRC/pipeline_data/lshtm_outputs/cases_deaths", component="cases_base")
             cases_base[8,]$lower
        shell: sudo Rscript {0}

