name: LSHTM Model

on: [ push ]

jobs:
  build:
    name : ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
          fail-fast: false
          matrix:
            os:  ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install R (Ubuntu)
        run : |
              sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
              sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/'
              sudo apt update
              sudo apt install r-base r-base-core r-recommended
        if: matrix.os == 'ubuntu-latest'

      - name: Install R (macOS)
        run : |
              brew install r gdal openssl hdf5 udunits proj
              brew link openssl --force
        if: matrix.os == 'macos-latest'

      - name : Install System Requirements (Ubuntu)
        run : sudo apt-get install libxml2-dev libcurl4-openssl-dev libnlopt-dev curl libgsl-dev libhdf5-dev libudunits2-dev libgdal-dev -y
        if: matrix.os == 'ubuntu-latest'

      - name: Install R library Requirements (Ubuntu)
        run: |
             sudo apt-get install apt-transport-https software-properties-common -y
        if: matrix.os == 'ubuntu-latest'

      - name: Install Required Libraries
        env: 
              DEBIAN_FRONTEND: noninteractive
        run: sudo Rscript SCRC/R/requirements.R

      - name: Run Model Locally in Dump Mode
        run: Rscript run_model.R 1 --local --dump

      - name: Test Outputs
        run: Rscript tests/regression/test_params.R
      
      - name: Install Pip and Require Modules
        run : |
              sudo apt-get install python3-pip python3-setuptools
              sudo pip3 install pandas dataclasses
        if: matrix.os == 'ubuntu-latest'

      - name: Test Local Vanilla Model Run (Region = Glasgow City, 10 realisations)
        run: Rscript run_model.R 10 --local

      - name: Install SCRC Data Pipeline
        run : |
              sudo pip3 install -r SCRC/Python/requirements.txt
        if: matrix.os == 'ubuntu-latest'

      - name: Fetch Data via API
        run: python -m data_pipeline_api.registry.download --config SCRC/pipeline_data/config.yaml

      - name: Test Remote Vanilla Model Run (Region = Glasgow City, 10 realisations)
        run: Rscript run_model.R 10

      - name: Test Output Files
        run: |
             library(SCRCdataAPI)
             dyn_sum_base <- read_table(file="local_test.h5", path="SCRC/pipeline_data/lshtm_outputs/dynamics_summary", component="base")
             dyn_sum_base[1,]$lower
             dyn_ts_base_R <- read_table(file="local_test.h5", path="SCRC/pipeline_data/lshtm_outputs/dynamics_time_series", component="Base_R_time_series")
             dyn_ts_base_R[1,][[366]]
             cases_base <- read_table(file="local_test.h5", path="SCRC/pipeline_data/lshtm_outputs/cases_deaths", component="cases_base")
             cases_base[8,]$lower
        shell: sudo Rscript {0}

